"""Git operations for the knowledge base.

``GitManager`` is instantiated with the repository root (usually
``kb_root``).  Call ``commit()`` after every write-through operation.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Optional


class GitError(RuntimeError):
    """Raised when a ``git`` command fails."""


# Runtime system files/folders auto-generated by the app at the repo root
# (heartbeat, event log, lock, macOS metadata).  They are never committed and
# must not count as "uncommitted changes", so the workspace stays "clean".
#
# 维护说明：若在仓库根目录新增运行时文件（心跳/缓存/锁等），请同步到此处。
# 更稳的是用下面的 _is_system_noise() —— 它额外把「根目录下以 . 开头的隐藏
# 文件/目录」统一当作运行时噪音，未来新增 . 开头运行时文件无需再改这里。
# 用户知识库内容永远在 common-knowledge/、projects/、archive/ 下，不以 . 开头，
# 因此不会误伤。
SYSTEM_NOISE_PREFIXES = (".mcp-heartbeat", ".events/", ".DS_Store", ".lock")


def _is_system_noise(path: str) -> bool:
    """Return True for runtime system files that must not count as KB changes.

    Two sources: the explicit :data:`SYSTEM_NOISE_PREFIXES` list, plus a generic
    rule that any top-level hidden file/folder (its first path segment starts
    with ``.``) is treated as runtime noise.  User KB content always lives under
    ``common-knowledge/``, ``projects/``, ``archive/`` so it never starts with
    ``.`` and is never misclassified.
    """
    if any(path.startswith(p) for p in SYSTEM_NOISE_PREFIXES):
        return True
    return path.lstrip("/").split("/", 1)[0].startswith(".")


class GitManager:
    """Wrap ``git`` operations for a knowledge base directory."""

    def __init__(self, repo_root: Path) -> None:
        self.repo = repo_root.resolve()

    # ── low-level runner ─────────────────────────────────────

    def _run(self, *args: str, check: bool = True) -> str:
        try:
            r = subprocess.run(
                ["git"] + list(args),
                cwd=str(self.repo),
                capture_output=True,
                text=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired:
            raise GitError("git command timed out")
        except FileNotFoundError:
            raise GitError("git binary not found on PATH")

        if check and r.returncode != 0:
            raise GitError(f"git {' '.join(args)} failed:\n{r.stderr.strip()}")
        return r.stdout.strip()

    def _run_bytes(self, *args: str) -> bytes:
        """Run git and return raw stdout bytes (no whitespace stripping).

        Needed for ``--porcelain -z`` NUL-separated status output, where the
        leading space of the first record's status column is meaningful and
        ``str.strip()`` (as in :meth:`_run`) would silently corrupt it.
        """
        try:
            r = subprocess.run(
                ["git"] + list(args),
                cwd=str(self.repo),
                capture_output=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired:
            raise GitError("git command timed out")
        except FileNotFoundError:
            raise GitError("git binary not found on PATH")
        if r.returncode != 0:
            err = r.stderr.decode("utf-8", "replace").strip()
            raise GitError(f"git {' '.join(args)} failed:\n{err}")
        return r.stdout

    # ── lifecycle ────────────────────────────────────────────

    def init(self) -> None:
        """Initialize the repo if not already a git directory."""
        if (self.repo / ".git").exists():
            return
        self._run("init")
        self._run("config", "user.name", "myknowledge")
        self._run("config", "user.email", "myknowledge@local")

    def is_initialized(self) -> bool:
        return (self.repo / ".git").is_dir()

    # ── commit ───────────────────────────────────────────────

    def commit(self, message: str) -> Optional[str]:
        """``git add -A`` + ``git commit``.

        Returns the commit hash, or ``None`` if nothing to commit.
        Raises ``GitError`` on failure.
        """
        self._run("add", "-A")

        status = self._run("status", "--porcelain")
        if not status:
            return None

        self._run("commit", "-m", message)
        return self.get_head_hash()

    # ── head & log ───────────────────────────────────────────

    def get_head_hash(self) -> Optional[str]:
        try:
            return self._run("rev-parse", "HEAD")
        except GitError:
            return None

    def log(self, n: int = 5) -> str:
        """Last *n* commits (oneline)."""
        return self._run("log", f"-{n}", "--oneline")

    def has_uncommitted_changes(self) -> bool:
        try:
            return bool(self._run("status", "--porcelain"))
        except GitError:
            return False

    def worktree_status(self) -> list[tuple[str, str]]:
        """Return filtered ``git status --porcelain -z`` entries.

        Excludes runtime system files (heartbeat, events, lock, .DS_Store)
        so they don't pollute the "uncommitted changes" judgment.

        Uses NUL-separated porcelain (``-z``) so paths are parsed exactly:
        - no leading-space corruption from :meth:`_run`'s ``.strip()``
        - no quoted-path ambiguity
        - rename records (``R``) yield the *destination* (new) path

        Returns a list of ``(xy, path)`` tuples, e.g. ``("??", "common-knowledge/draft.md")``.
        """
        try:
            # --untracked-files=all lists each untracked file individually
            # (otherwise git collapses an untracked dir to "dir/").
            raw = self._run_bytes("status", "--porcelain", "-z", "--untracked-files=all")
        except GitError:
            return []
        entries: list[tuple[str, str]] = []
        records = [r for r in raw.split(b"\x00") if r]
        i = 0
        while i < len(records):
            rec = records[i]
            # Header records look like b"XY <path>" (status + separator space).
            if len(rec) < 3 or rec[2:3] != b" ":
                i += 1
                continue
            xy = rec[:2].decode("utf-8", "replace")
            path = rec[3:].decode("utf-8", "replace")
            i += 1
            # For a rename, the header holds the destination path and the
            # *next* NUL record holds the source path; use the destination.
            if xy.startswith("R"):
                i += 1
            if not path or _is_system_noise(path):
                continue
            entries.append((xy, path))
        return entries

    # ── diff ─────────────────────────────────────────────────

    def read_diff(self, from_hash: str, to_hash: Optional[str] = None) -> str:
        """Diff between two commits, or against working tree."""
        args = ["diff", from_hash]
        if to_hash:
            args.append(to_hash)
        return self._run(*args)

    def read_worktree_diff(self) -> str:
        """Diff between HEAD and the working tree (uncommitted changes).

        等价于 ``git diff HEAD``，包含已跟踪文件的未暂存+已暂存改动。
        注意：不包含未跟踪（untracked）文件，除非先 git add。
        """
        return self._run("diff", "HEAD")

    def read_worktree_diff_full(self, untracked_paths: list[str]) -> str:
        """Worktree diff that also includes untracked files' content.

        ``git diff HEAD`` cannot see untracked files.  For those we render a
        synthetic ``+``-only diff via ``git diff --no-index /dev/null <file>``
        so the AI can read the actual draft content.
        """
        parts = []
        if self.get_head_hash():
            # Only meaningful once the repo has at least one commit.
            try:
                tracked = self.read_worktree_diff()
            except GitError:
                tracked = ""
            if tracked.strip():
                parts.append(tracked)
        for path in untracked_paths:
            try:
                # --no-index returns exit code 1 when files differ; check=False
                d = self._run("diff", "--no-index", "/dev/null", path, check=False)
            except GitError:
                d = ""
            if d.strip():
                parts.append(d)
        return "\n".join(parts)

    # ── checkpoint ───────────────────────────────────────────

    def write_checkpoint(self, commit_hash: str, checkpoint_file: Path) -> None:
        """Write the agent-processed commit hash."""
        checkpoint_file.write_text(commit_hash.strip(), encoding="utf-8")

    def read_checkpoint(self, checkpoint_file: Path) -> Optional[str]:
        """Read the checkpoint, or ``None`` if missing."""
        if not checkpoint_file.exists():
            return None
        return checkpoint_file.read_text(encoding="utf-8").strip()

    def diff_from_checkpoint(self, checkpoint_file: Path) -> Optional[str]:
        """Return diff from checkpoint to HEAD."""
        cp = self.read_checkpoint(checkpoint_file)
        if not cp:
            return None
        return self.read_diff(cp, self.get_head_hash() or "HEAD")
